# Site settings
title: TU Delft DCC
email: support4research@tudelft.nl
description: > # this means to ignore newlines until "baseurl:"
  TU Delft Digital Competence Centre temporary website
  # for Google search results and feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://DCC.tudelft.nl" # the base hostname & protocol for your site
github_username:  TU-Delft-DCC

# Build settings
markdown: kramdown
