# Site settings
title: TU Delft DCC
email: dcc@tudelft.nl
description: > # this means to ignore newlines until "baseurl:"
  TU Delft Digital Competence Centre temporary website
  # for Google search results and feed.xml site description
baseurl: "/DCC-website" # the subpath of your site, e.g. /blog/
url: "https://tu-delft-dcc.github.io" # the base hostname & protocol for your site
github_username:  TU-Delft-DCC

# Build settings
markdown: kramdown

include: ['_pages']

collections:
  pages:
    output: true
